#### IMPORTING LIBRARIES

In [1]:
import pandas as pd;

##### IMPORTING DATA

In [2]:
nav_history=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\02_nav_history.csv")
investor_transactions=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\08_investor_transactions.csv")
scheme_performance=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\07_scheme_performance.csv")
fund_master=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\01_fund_master.csv")

###### NAV_HISTORY

In [3]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
# Checking data types
nav_history.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [5]:
# Checking for duplicates
nav_history.duplicated().sum()

np.int64(0)

In [6]:
# checking missing values
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [7]:
# validating nav > 0
nav_history[nav_history['nav']<=0]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [8]:
# changing the STR data type of date into DATE data type
nav_history['date']=pd.to_datetime(
    nav_history['date'])

In [9]:
# Arranging the data in amfi_code and date order
nav_history=nav_history.sort_values(by=['amfi_code','date'],ascending=True)
nav_history

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

##### INVESTOR_TRANSACTIONS

In [10]:
investor_transactions.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [11]:
investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [12]:
# correcting the transaction date column into DATE data type
investor_transactions['transaction_date']=pd.to_datetime(
    investor_transactions['transaction_date'])

In [13]:
# checking any amounts less than zero exists
investor_transactions[investor_transactions['amount_inr']<=0]

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, transaction_type, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status]
Index: []

In [14]:
# checking values in kyc status
investor_transactions['kyc_status'].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

##### SCHEME PERFORMANCE

In [15]:
scheme_performance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [16]:
scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [17]:
# validating expense ratio pct
scheme_performance[scheme_performance['expense_ratio_pct']<=0.1]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [18]:
investor_transactions["transaction_type"] = investor_transactions["transaction_type"].replace("Sip", "SIP")
investor_transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [19]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [20]:
fund_master['launch_date']=pd.to_datetime(fund_master['launch_date'])

In [21]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [22]:
nav_history.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [23]:
investor_transactions.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [24]:
scheme_performance.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [25]:
aum_by_fund_house = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")

In [26]:
aum_by_fund_house['date']=pd.to_datetime(aum_by_fund_house['date'])
aum_by_fund_house.dtypes

date              datetime64[us]
fund_house                   str
aum_lakh_crore           float64
aum_crore                  int64
num_schemes                int64
dtype: object

In [27]:
aum_by_fund_house.columns

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

##### IMPORTING NEW LIBRARY

In [28]:
from sqlalchemy import create_engine

In [29]:
# creating engine
engine = create_engine("sqlite:///../bluestock_mf.db")

In [30]:
# CREATING dim_fund table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE dim_fund(
    amfi_code INTEGER PRIMARY KEY,
    fund_house TEXT,
    scheme_name TEXT,
    category TEXT,
    sub_category TEXT,
    plan TEXT,
    launch_date TEXT,
    benchmark TEXT,
    expense_ratio_pct REAL,
    exit_load_pct REAL,
    min_sip_amount INTEGER,
    min_lumpsum_amount INTEGER,
    fund_manager TEXT,
    risk_category TEXT,
    sebi_category_code TEXT
    )""")
    conn.commit()

OperationalError: (sqlite3.OperationalError) table dim_fund already exists
[SQL:
    CREATE TABLE dim_fund(
    amfi_code INTEGER PRIMARY KEY,
    fund_house TEXT,
    scheme_name TEXT,
    category TEXT,
    sub_category TEXT,
    plan TEXT,
    launch_date TEXT,
    benchmark TEXT,
    expense_ratio_pct REAL,
    exit_load_pct REAL,
    min_sip_amount INTEGER,
    min_lumpsum_amount INTEGER,
    fund_manager TEXT,
    risk_category TEXT,
    sebi_category_code TEXT
    )]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
# creating dim_table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE dim_date(
     date_id INTEGER PRIMARY KEY,
    full_date TEXT,
    year INTEGER,
    month INTEGER,
    month_name TEXT,
    quarter INTEGER,
    day_of_week TEXT,
    is_weekend INTEGER
    )""")
    conn.commit()

In [ ]:
# creating fact_nav
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_nav(
    nav_id INTEGER PRIMARY KEY,
    amfi_code INTEGER,
    date_id INTEGER,
    nav REAL,
    FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code),
    FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
    )""")
    conn.commit()

In [ ]:
# creating fact_transactions
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_transactions (
    transaction_id INTEGER PRIMARY KEY,
    investor_id TEXT,
    amfi_code INTEGER,
    date_id INTEGER,
    transaction_type TEXT,
    amount_inr INTEGER,
    state TEXT,
    city TEXT,
    city_tier TEXT,
    age_group TEXT,
    gender TEXT,
    annual_income_lakh REAL,
    payment_mode TEXT,
    kyc_status TEXT,
    FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code),
    FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
    )""")
    conn.commit()

In [ ]:
# creating fact_performance table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_performance (
    performance_id INTEGER PRIMARY KEY,
    amfi_code INTEGER,
    return_1yr_pct REAL,
    return_3yr_pct REAL,
    return_5yr_pct REAL,
    benchmark_3yr_pct REAL,
    alpha REAL,
    beta REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    std_dev_ann_pct REAL,
    max_drawdown_pct REAL,
    aum_crore INTEGER,
    expense_ratio_pct REAL,
    morningstar_rating INTEGER,
    risk_grade TEXT,
    FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code)
    )""")
    conn.commit()

In [ ]:
# creating fact_aum table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_aum (
    aum_id INTEGER PRIMARY KEY,
    date_id INTEGER,
    fund_house TEXT,
    aum_lakh_crore REAL,
    aum_crore INTEGER,
    num_schemes INTEGER,
    FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
    )""")
    conn.commit()

In [31]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", engine)

                name
0           dim_fund
1           dim_date
2           fact_nav
3  fact_transactions
4   fact_performance
5           fact_aum

In [32]:
# inserting table data into sql database
fund_master.to_sql("dim_fund", engine, if_exists="append", index=False)

DatabaseError: Execution failed on sql 'INSERT INTO dim_fund (amfi_code, fund_house, scheme_name, category, sub_category, plan, launch_date, benchmark, expense_ratio_pct, exit_load_pct, min_sip_amount, min_lumpsum_amount, fund_manager, risk_category, sebi_category_code) VALUES (:amfi_code, :fund_house, :scheme_name, :category, :sub_category, :plan, :launch_date, :benchmark, :expense_ratio_pct, :exit_load_pct, :min_sip_amount, :min_lumpsum_amount, :fund_manager, :risk_category, :sebi_category_code)': (sqlite3.IntegrityError) UNIQUE constraint failed: dim_fund.amfi_code
[SQL: INSERT INTO dim_fund (amfi_code, fund_house, scheme_name, category, sub_category, "plan", launch_date, benchmark, expense_ratio_pct, exit_load_pct, min_sip_amount, min_lumpsum_amount, fund_manager, risk_category, sebi_category_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [(119551, 'SBI Mutual Fund', 'SBI Bluechip Fund - Regular Plan - Growth', 'Equity', 'Large Cap', 'Regular', '2006-02-14 00:00:00.000000', 'NIFTY 100 TRI', 1.54, 1.0, 500, 1000, 'Sohini Andani', 'Moderate', 'EC01'), (119552, 'SBI Mutual Fund', 'SBI Bluechip Fund - Direct Plan - Growth', 'Equity', 'Large Cap', 'Direct', '2013-01-01 00:00:00.000000', 'NIFTY 100 TRI', 0.66, 1.0, 500, 1000, 'Sohini Andani', 'Moderate', 'EC01'), (119598, 'SBI Mutual Fund', 'SBI Small Cap Fund - Regular Plan - Growth', 'Equity', 'Small Cap', 'Regular', '2009-09-09 00:00:00.000000', 'BSE 250 SmallCap TRI', 1.43, 1.0, 500, 1000, 'R. Srinivasan', 'Very High', 'EC03'), (119599, 'SBI Mutual Fund', 'SBI Small Cap Fund - Direct Plan - Growth', 'Equity', 'Small Cap', 'Direct', '2013-01-01 00:00:00.000000', 'BSE 250 SmallCap TRI', 0.72, 1.0, 500, 1000, 'R. Srinivasan', 'Very High', 'EC03'), (119120, 'SBI Mutual Fund', 'SBI Magnum Gilt Fund - Regular Plan - Growth', 'Debt', 'Gilt', 'Regular', '2000-12-30 00:00:00.000000', 'CRISIL Dynamic Gilt Index', 0.77, 0.0, 500, 1000, 'Dinesh Ahuja', 'Low', 'DC02'), (100016, 'HDFC Mutual Fund', 'HDFC Top 100 Fund - Regular Plan - Growth', 'Equity', 'Large Cap', 'Regular', '1996-09-11 00:00:00.000000', 'NIFTY 100 TRI', 1.55, 1.0, 500, 1000, 'Rahul Baijal', 'Moderate', 'EC01'), (125497, 'HDFC Mutual Fund', 'HDFC Top 100 Fund - Direct Plan - Growth', 'Equity', 'Large Cap', 'Direct', '2013-01-01 00:00:00.000000', 'NIFTY 100 TRI', 0.92, 1.0, 500, 1000, 'Rahul Baijal', 'Moderate', 'EC01'), (100033, 'HDFC Mutual Fund', 'HDFC Mid-Cap Opportunities Fund - Regular - Growth', 'Equity', 'Mid Cap', 'Regular', '2007-06-25 00:00:00.000000', 'NIFTY Midcap 150 TRI', 1.38, 1.0, 500, 1000, 'Chirag Setalvad', 'High', 'EC02')  ... displaying 10 of 40 total bound parameter sets ...  (149323, 'DSP Mutual Fund', 'DSP Midcap Fund - Regular - Growth', 'Equity', 'Mid Cap', 'Regular', '2006-11-16 00:00:00.000000', 'NIFTY Midcap 150 TRI', 1.61, 1.0, 500, 1000, 'Vinit Sambre', 'High', 'EC02'), (149324, 'DSP Mutual Fund', 'DSP Small Cap Fund - Regular - Growth', 'Equity', 'Small Cap', 'Regular', '2007-06-14 00:00:00.000000', 'BSE 250 SmallCap TRI', 1.52, 1.0, 500, 1000, 'Vinit Sambre', 'Very High', 'EC03')]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [33]:
nav_history["date"].min(), nav_history["date"].max()

(Timestamp('2022-01-03 00:00:00'), Timestamp('2026-05-29 00:00:00'))

In [34]:
#creating a date range
date_range = pd.date_range(start="2022-01-01", end="2026-12-31", freq="D")
date_range

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25',
               '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=1826, freq='D')

In [35]:
dim_date = pd.DataFrame({
    "full_date": date_range.strftime("%Y-%m-%d"),
    "year": date_range.year,
    "month": date_range.month,
    "month_name": date_range.strftime("%B"),
    "quarter": date_range.quarter,
    "day_of_week": date_range.strftime("%A"),
    "is_weekend": date_range.dayofweek.isin([5, 6]).astype(int)
})

dim_date.head()

    full_date  year  month month_name  quarter day_of_week  is_weekend
0  2022-01-01  2022      1    January        1    Saturday           1
1  2022-01-02  2022      1    January        1      Sunday           1
2  2022-01-03  2022      1    January        1      Monday           0
3  2022-01-04  2022      1    January        1     Tuesday           0
4  2022-01-05  2022      1    January        1   Wednesday           0

In [36]:
dim_date.insert(0, "date_id", range(1, len(dim_date) + 1))
dim_date.head()

,date_id,full_date,year,month,month_name,quarter,day_of_week,is_weekend
0,1,2022-01-01,2022,1,January,1,Saturday,1
1,2,2022-01-02,2022,1,January,1,Sunday,1
2,3,2022-01-03,2022,1,January,1,Monday,0
3,4,2022-01-04,2022,1,January,1,Tuesday,0
4,5,2022-01-05,2022,1,January,1,Wednesday,0

In [37]:
# inseting data into dim_date 
dim_date.to_sql("dim_date", engine, if_exists="append", index=False)

DatabaseError: Execution failed on sql 'INSERT INTO dim_date (date_id, full_date, year, month, month_name, quarter, day_of_week, is_weekend) VALUES (:date_id, :full_date, :year, :month, :month_name, :quarter, :day_of_week, :is_weekend)': (sqlite3.IntegrityError) UNIQUE constraint failed: dim_date.date_id
[SQL: INSERT INTO dim_date (date_id, full_date, year, month, month_name, quarter, day_of_week, is_weekend) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [(1, '2022-01-01', 2022, 1, 'January', 1, 'Saturday', 1), (2, '2022-01-02', 2022, 1, 'January', 1, 'Sunday', 1), (3, '2022-01-03', 2022, 1, 'January', 1, 'Monday', 0), (4, '2022-01-04', 2022, 1, 'January', 1, 'Tuesday', 0), (5, '2022-01-05', 2022, 1, 'January', 1, 'Wednesday', 0), (6, '2022-01-06', 2022, 1, 'January', 1, 'Thursday', 0), (7, '2022-01-07', 2022, 1, 'January', 1, 'Friday', 0), (8, '2022-01-08', 2022, 1, 'January', 1, 'Saturday', 1)  ... displaying 10 of 1826 total bound parameter sets ...  (1825, '2026-12-30', 2026, 12, 'December', 4, 'Wednesday', 0), (1826, '2026-12-31', 2026, 12, 'December', 4, 'Thursday', 0)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [38]:
pd.read_sql("SELECT * FROM dim_date LIMIT 5;", engine)

,date_id,full_date,year,month,month_name,quarter,day_of_week,is_weekend
0,1,2022-01-01,2022,1,January,1,Saturday,1
1,2,2022-01-02,2022,1,January,1,Sunday,1
2,3,2022-01-03,2022,1,January,1,Monday,0
3,4,2022-01-04,2022,1,January,1,Tuesday,0
4,5,2022-01-05,2022,1,January,1,Wednesday,0

In [39]:
dim_date_lookup = pd.read_sql("SELECT date_id, full_date FROM dim_date;", engine)
dim_date_lookup["full_date"] = pd.to_datetime(dim_date_lookup["full_date"])
dim_date_lookup.head()

   date_id  full_date
0        1 2022-01-01
1        2 2022-01-02
2        3 2022-01-03
3        4 2022-01-04
4        5 2022-01-05

In [40]:
# inserting data inside fact_nav
fact_nav = nav_history.merge(dim_date_lookup, left_on="date", right_on="full_date", how="left")
fact_nav.head()

   amfi_code       date       nav  date_id  full_date
0     100016 2022-01-03  520.4608        3 2022-01-03
1     100016 2022-01-04  515.0971        4 2022-01-04
2     100016 2022-01-05  521.7239        5 2022-01-05
3     100016 2022-01-06  515.7880        6 2022-01-06
4     100016 2022-01-07  515.1639        7 2022-01-07

In [41]:
fact_nav = fact_nav[["amfi_code", "date_id", "nav"]]
fact_nav.head()

   amfi_code  date_id       nav
0     100016        3  520.4608
1     100016        4  515.0971
2     100016        5  521.7239
3     100016        6  515.7880
4     100016        7  515.1639

In [42]:
fact_nav.to_sql("fact_nav",engine, if_exists='append',index=False)
pd.read_sql("SELECT * FROM fact_nav LIMIT 5;", engine)

   nav_id  amfi_code  date_id       nav
0       1     100016        3  520.4608
1       2     100016        4  515.0971
2       3     100016        5  521.7239
3       4     100016        6  515.7880
4       5     100016        7  515.1639

In [43]:
investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [44]:
dim_date_lookup.head()

   date_id  full_date
0        1 2022-01-01
1        2 2022-01-02
2        3 2022-01-03
3        4 2022-01-04
4        5 2022-01-05

In [45]:
# merging the tables
fact_transactions=investor_transactions.merge(dim_date_lookup,left_on ='transaction_date',right_on='full_date',how='left')
fact_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status,date_id,full_date
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified,731,2024-01-01
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified,731,2024-01-01
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified,731,2024-01-01
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending,731,2024-01-01
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending,731,2024-01-01

In [46]:
# removing unwanted columns (transaction_date,full_dates)
fact_transactions=fact_transactions[['investor_id','amfi_code','date_id','transaction_type','amount_inr','state','city','city_tier',
                                     'age_group','gender','annual_income_lakh','payment_mode','kyc_status']]
fact_transactions.head()

,investor_id,amfi_code,date_id,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,119092,731,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,148567,731,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,118636,731,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,118634,731,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,119094,731,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [47]:
# loading data into sql fact_transaction
fact_transactions.to_sql("fact_transactions", engine, if_exists="append", index=False)
pd.read_sql("SELECT * FROM fact_transactions LIMIT 5;", engine)

,transaction_id,investor_id,amfi_code,date_id,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,1,INV003054,119092,731,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,2,INV002952,148567,731,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,3,INV003420,118636,731,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,4,INV003436,118634,731,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,5,INV004691,119094,731,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [48]:
scheme_performance.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [49]:
# Drop duplicate columns (columns already in dim_fund)
fact_performance = scheme_performance.drop(columns=["scheme_name", "fund_house", "category", "plan"])
fact_performance.head()

,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [50]:
# loading data 
fact_performance.to_sql("fact_performance", engine, if_exists="append", index=False)
pd.read_sql("SELECT * FROM fact_performance LIMIT 5;",engine)

,performance_id,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,1,119551,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,2,119552,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,3,119598,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,4,119599,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,5,119120,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [51]:
# importing aum_by_fund_house data
aum_by_fund_house=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\03_aum_by_fund_house.csv")
aum_by_fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [52]:
aum_by_fund_house.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [53]:
# changing date into Date data ype
aum_by_fund_house['date']=pd.to_datetime(aum_by_fund_house['date'])

In [54]:
dim_date_lookup.head()

   date_id  full_date
0        1 2022-01-01
1        2 2022-01-02
2        3 2022-01-03
3        4 2022-01-04
4        5 2022-01-05

In [55]:
# merging for including date_id column in aum
fact_aum=aum_by_fund_house.merge(dim_date_lookup,left_on='date',right_on='full_date',how='left')
fact_aum.head()

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,date_id,full_date
0,2022-03-31,SBI Mutual Fund,6.05,605000,186,90,2022-03-31
1,2022-03-31,ICICI Prudential MF,4.65,465000,216,90,2022-03-31
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195,90,2022-03-31
3,2022-03-31,Nippon India MF,2.70,270000,177,90,2022-03-31
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168,90,2022-03-31

In [56]:
fact_aum = fact_aum[["date_id", "fund_house", "aum_lakh_crore", "aum_crore", "num_schemes"]]
fact_aum.head()

   date_id           fund_house  aum_lakh_crore  aum_crore  num_schemes
0       90      SBI Mutual Fund            6.05     605000          186
1       90  ICICI Prudential MF            4.65     465000          216
2       90     HDFC Mutual Fund            4.35     435000          195
3       90      Nippon India MF            2.70     270000          177
4       90    Kotak Mahindra MF            2.70     270000          168

In [57]:
fact_aum.to_sql("fact_aum", engine, if_exists="append", index=False)
pd.read_sql('SELECT * FROM fact_aum LIMIT 5;',engine)

,aum_id,date_id,fund_house,aum_lakh_crore,aum_crore,num_schemes
0,1,90,SBI Mutual Fund,6.05,605000,186
1,2,90,ICICI Prudential MF,4.65,465000,216
2,3,90,HDFC Mutual Fund,4.35,435000,195
3,4,90,Nippon India MF,2.70,270000,177
4,5,90,Kotak Mahindra MF,2.70,270000,168

In [58]:
print("dim_fund:", pd.read_sql("SELECT COUNT(*) FROM dim_fund;", engine).iloc[0,0], "vs fund_master:", fund_master.shape[0])
print("fact_nav:", pd.read_sql("SELECT COUNT(*) FROM fact_nav;", engine).iloc[0,0], "vs nav_history:", nav_history.shape[0])
print("fact_transactions:", pd.read_sql("SELECT COUNT(*) FROM fact_transactions;", engine).iloc[0,0], "vs investor_transactions:", investor_transactions.shape[0])
print("fact_performance:", pd.read_sql("SELECT COUNT(*) FROM fact_performance;", engine).iloc[0,0], "vs scheme_performance:", scheme_performance.shape[0])
print("fact_aum:", pd.read_sql("SELECT COUNT(*) FROM fact_aum;", engine).iloc[0,0], "vs aum_by_fund_house:", aum_by_fund_house.shape[0])

dim_fund: 40 vs fund_master: 40
fact_nav: 138000 vs nav_history: 46000
fact_transactions: 98334 vs investor_transactions: 32778
fact_performance: 80 vs scheme_performance: 40
fact_aum: 270 vs aum_by_fund_house: 90

In [59]:
with engine.connect() as conn:
    conn.exec_driver_sql("DELETE FROM fact_performance;")
    conn.exec_driver_sql("DELETE FROM fact_aum;")
    conn.commit()

In [60]:
fact_performance.to_sql("fact_performance", engine, if_exists="append", index=False)
fact_aum.to_sql("fact_aum", engine, if_exists="append", index=False)

90

In [61]:
print("fact_performance:", pd.read_sql("SELECT COUNT(*) FROM fact_performance;", engine).iloc[0,0], "vs scheme_performance:", scheme_performance.shape[0])
print("fact_aum:", pd.read_sql("SELECT COUNT(*) FROM fact_aum;", engine).iloc[0,0], "vs aum_by_fund_house:", aum_by_fund_house.shape[0])

fact_performance: 40 vs scheme_performance: 40
fact_aum: 90 vs aum_by_fund_house: 90

#### ANALYTICAL SQL QUERIES

####  1. Top 5 funds by AUM

In [62]:
fact_performance.head()

,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [63]:
pd.read_sql(
    "SELECT d.fund_house, SUM(p.aum_crore) AS AUM "
    "FROM dim_fund d LEFT JOIN fact_performance p ON d.amfi_code = p.amfi_code "
    "GROUP BY d.fund_house "
    "ORDER BY SUM(p.aum_crore) DESC "
    "LIMIT 5;",
    engine
)

                 fund_house     AUM
0           Nippon India MF  154328
1         Kotak Mahindra MF  145689
2       ICICI Prudential MF  120241
3           DSP Mutual Fund  114787
4  Aditya Birla Sun Life MF  104108

####  2. Average NAV per month

In [64]:
fact_nav.head()

   amfi_code  date_id       nav
0     100016        3  520.4608
1     100016        4  515.0971
2     100016        5  521.7239
3     100016        6  515.7880
4     100016        7  515.1639

In [65]:
dim_date.head()

,date_id,full_date,year,month,month_name,quarter,day_of_week,is_weekend
0,1,2022-01-01,2022,1,January,1,Saturday,1
1,2,2022-01-02,2022,1,January,1,Sunday,1
2,3,2022-01-03,2022,1,January,1,Monday,0
3,4,2022-01-04,2022,1,January,1,Tuesday,0
4,5,2022-01-05,2022,1,January,1,Wednesday,0

In [66]:
pd.read_sql(
    "SELECT d.year, d.month, AVG(n.nav) AS avg_nav "
    "FROM dim_date d LEFT JOIN fact_nav n ON d.date_id = n.date_id "
    "GROUP BY d.year, d.month "
    "ORDER BY d.year, d.month;",
    engine
)

    year  month     avg_nav
0   2022      1  207.061394
1   2022      2  207.717759
2   2022      3  209.692614
3   2022      4  211.833458
4   2022      5  212.731451
5   2022      6  213.860867
6   2022      7  213.956111
7   2022      8  215.683994
8   2022      9  218.494308
9   2022     10  219.529633
10  2022     11  223.470692
11  2022     12  226.760632
12  2023      1  230.671234
13  2023      2  233.847674
14  2023      3  238.009623
15  2023      4  240.613317
16  2023      5  241.892889
17  2023      6  244.605453
18  2023      7  245.780681
19  2023      8  247.734606
20  2023      9  251.833677
21  2023     10  255.607027
22  2023     11  258.352467
23  2023     12  262.020325
24  2024      1  264.620575
25  2024      2  266.331713
26  2024      3  269.597812
27  2024      4  271.300039
28  2024      5  273.450521
29  2024      6  275.465499
30  2024      7  279.024099
31  2024      8  279.736082
32  2024      9  281.016961
33  2024     10  282.127765
34  2024     11  285.243625
35  2024     12  285.272562
36  2025      1  288.038374
37  2025      2  291.744584
38  2025      3  296.158074
39  2025      4  299.412965
40  2025      5  303.939743
41  2025      6  306.879948
42  2025      7  309.726327
43  2025      8  313.180407
44  2025      9  316.132001
45  2025     10  321.449971
46  2025     11  325.681151
47  2025     12  331.733029
48  2026      1  337.117471
49  2026      2  342.076357
50  2026      3  347.187520
51  2026      4  355.025381
52  2026      5  357.039198
53  2026      6         NaN
54  2026      7         NaN
55  2026      8         NaN
56  2026      9         NaN
57  2026     10         NaN
58  2026     11         NaN
59  2026     12         NaN

#### 3: SIP Year-over-Year growth

In [67]:
fact_transactions.head()

,investor_id,amfi_code,date_id,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,119092,731,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,148567,731,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,118636,731,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,118634,731,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,119094,731,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [68]:
pd.read_sql(
    "WITH SIP AS ( "
    "SELECT d.year as year, SUM(t.amount_inr) AS SIP_TOTAL "
    "FROM dim_date d LEFT JOIN fact_transactions t ON d.date_id = t.date_id "
    "WHERE t.transaction_type = 'SIP' "
    "GROUP BY d.year "
    "ORDER BY d.year) "
    "SELECT year, SIP_TOTAL, "
    "(SIP_TOTAL - LAG(SIP_TOTAL, 1) OVER (ORDER BY year)) * 100.0 / LAG(SIP_TOTAL, 1) OVER (ORDER BY year) AS YOY_GROWTH "
    "FROM SIP;",
    engine
)

   year  SIP_TOTAL  YOY_GROWTH
0  2024  459699156         NaN
1  2025  192001317  -58.233267

#### 4. Total transactions by state

In [69]:
pd.read_sql(
    "SELECT state,COUNT(*) AS transactions FROM fact_transactions "
    "GROUP BY state; ",engine)

             state  transactions
0            Delhi          8031
1          Gujarat          8340
2          Haryana          8208
3        Karnataka          7863
4   Madhya Pradesh          8793
5      Maharashtra          7572
6           Punjab          8895
7        Rajasthan          7731
8       Tamil Nadu          8418
9        Telangana          8154
10   Uttar Pradesh          8085
11     West Bengal          8244

####  5. Funds with expense_ratio < 1%

In [70]:
with engine.connect() as conn:
    conn.exec_driver_sql("DELETE FROM fact_performance;")
    conn.commit()

fact_performance.to_sql("fact_performance", engine, if_exists="append", index=False)

40

In [71]:
pd.read_sql(
    "SELECT f.scheme_name, f.fund_house, p.expense_ratio_pct "
    "FROM fact_performance p "
    "LEFT JOIN dim_fund f ON p.amfi_code = f.amfi_code "
    "WHERE p.expense_ratio_pct < 1 "
    "ORDER BY p.expense_ratio_pct;",
    engine
)

,scheme_name,fund_house,expense_ratio_pct
0,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,0.55
1,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,0.56
2,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,0.60
3,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,0.66
4,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,0.72
5,Nippon India Large Cap Fund - Direct - Growth,Nippon India MF,0.72
6,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,0.74
7,Axis Bluechip Fund - Direct - Growth,Axis Mutual Fund,0.75
8,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,0.77
9,HDFC Mid-Cap Opportunities Fund - Direct - Growth,HDFC Mutual Fund,0.78
10,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,0.79
11,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,0.80
12,Nippon India ETF Nifty 50 BeES,Nippon India MF,0.89
13,HDFC Top 100 Fund - Direct Plan - Growth,HDFC Mutual Fund,0.92

#### 6. Top 5 fund houses by total AUM

In [72]:
pd.read_sql(
    "SELECT fund_house,SUM(aum_crore) AS AUM "
    "FROM fact_aum "
    "GROUP BY fund_house "
    "ORDER BY SUM(aum_crore) DESC "
    "LIMIT 5;",
    engine)

            fund_house      AUM
0      SBI Mutual Fund  8491000
1  ICICI Prudential MF  6293000
2     HDFC Mutual Fund  5732000
3      Nippon India MF  3909000
4    Kotak Mahindra MF  3502000

#### 7: Number of transactions by KYC status

In [73]:
fact_transactions.head()
pd.read_sql(
    "select kyc_status,count(*) as transactions "
    "from fact_transactions "
    "group by kyc_status; ",
    engine)

  kyc_status  transactions
0    Pending          7896
1   Verified         90438

#### 8. Average 1-year return by category

In [74]:
pd.read_sql(
    "select f.category,avg(p.return_1yr_pct) as avg_1_year_return "
    "from dim_fund f left join fact_performance p on f.amfi_code=p.amfi_code "
    "group by f.category; ",
    engine)

  category  avg_1_year_return
0     Debt           6.281667
1   Equity          15.804412

#### 9: Funds with highest Sharpe ratio

In [75]:
pd.read_sql(
    "SELECT f.scheme_name, f.fund_house, p.sharpe_ratio "
    "FROM fact_performance p "
    "LEFT JOIN dim_fund f ON p.amfi_code = f.amfi_code "
    "ORDER BY p.sharpe_ratio DESC "
    "LIMIT 10;",
    engine
)

,scheme_name,fund_house,sharpe_ratio
0,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,7.68
1,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,6.18
2,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,5.14
3,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,1.84
4,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,1.52
5,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,1.33
6,HDFC Top 100 Fund - Regular Plan - Growth,HDFC Mutual Fund,1.06
7,Mirae Asset Large Cap Fund - Regular - Growth,Mirae Asset MF,1.06
8,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,1.03
9,Nippon India Large Cap Fund - Regular - Growth,Nippon India MF,1.00

#### 10: Monthly transaction volume trend

In [77]:
pd.read_sql(
    "select d.year,d.month,count(t.transaction_id) as transactons "
    "from dim_date d left join fact_transactions t on d.date_id=t.date_id "
    "group by d.year,d.month "
    "order by d.year,d.month; ",
    engine)

    year  month  transactons
0   2022      1            0
1   2022      2            0
2   2022      3            0
3   2022      4            0
4   2022      5            0
5   2022      6            0
6   2022      7            0
7   2022      8            0
8   2022      9            0
9   2022     10            0
10  2022     11            0
11  2022     12            0
12  2023      1            0
13  2023      2            0
14  2023      3            0
15  2023      4            0
16  2023      5            0
17  2023      6            0
18  2023      7            0
19  2023      8            0
20  2023      9            0
21  2023     10            0
22  2023     11            0
23  2023     12            0
24  2024      1         5847
25  2024      2         5583
26  2024      3         5922
27  2024      4         5856
28  2024      5         5703
29  2024      6         5967
30  2024      7         5904
31  2024      8         5955
32  2024      9         5499
33  2024     10         5871
34  2024     11         5589
35  2024     12         5934
36  2025      1         6060
37  2025      2         5262
38  2025      3         5919
39  2025      4         5577
40  2025      5         5886
41  2025      6            0
42  2025      7            0
43  2025      8            0
44  2025      9            0
45  2025     10            0
46  2025     11            0
47  2025     12            0
48  2026      1            0
49  2026      2            0
50  2026      3            0
51  2026      4            0
52  2026      5            0
53  2026      6            0
54  2026      7            0
55  2026      8            0
56  2026      9            0
57  2026     10            0
58  2026     11            0
59  2026     12            0

### CLEANING BALANCE 7 TABLES

##### IMPORTING DATA SETS TO CLEAN

In [78]:
fund_master=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\01_fund_master.csv")
aum_by_fund_house=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\03_aum_by_fund_house.csv")
monthly_sip_inflows=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\04_monthly_sip_inflows.csv")
category_inflows=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\05_category_inflows.csv")
industry_folio_counts=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\06_industry_folio_count.csv")
portfolio_holding=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\09_portfolio_holdings.csv")
benchmark_indices=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\10_benchmark_indices.csv")

##### fund_master

In [80]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [83]:
fund_master['launch_date']=pd.to_datetime(fund_master['launch_date'])
fund_master.dtypes

amfi_code                      int64
fund_house                       str
scheme_name                      str
category                         str
sub_category                     str
plan                             str
launch_date           datetime64[us]
benchmark                        str
expense_ratio_pct            float64
exit_load_pct                float64
min_sip_amount                 int64
min_lumpsum_amount             int64
fund_manager                     str
risk_category                    str
sebi_category_code               str
dtype: object

In [85]:
fund_master.duplicated().sum()

np.int64(0)

In [90]:
fund_master['fund_house'].unique()

<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [93]:
fund_master.to_csv(
    r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\fund_master_cleaned.csv",
    index=False
)

##### aum_by_fund_house

In [95]:
aum_by_fund_house.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [98]:
aum_by_fund_house['date']=pd.to_datetime(
    aum_by_fund_house['date'])
aum_by_fund_house.dtypes

date              datetime64[us]
fund_house                   str
aum_lakh_crore           float64
aum_crore                  int64
num_schemes                int64
dtype: object

In [100]:
aum_by_fund_house.to_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\aum_by_fund_house_cleaned.csv",
                         index=False)

##### monthly_sip_inflows

In [102]:
monthly_sip_inflows.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [104]:
monthly_sip_inflows.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [106]:
monthly_sip_inflows.duplicated().sum()

np.int64(0)

In [112]:
monthly_sip_inflows.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01-01,11517,4.91,9.10,4.80,NaN
1,2022-02-01,11438,4.93,8.20,4.85,NaN
2,2022-03-01,12328,5.09,10.50,5.01,NaN
3,2022-04-01,11863,5.48,9.52,5.12,NaN
4,2022-05-01,12286,5.55,8.10,5.15,NaN

In [114]:
monthly_sip_inflows['month'] = pd.to_datetime(monthly_sip_inflows['month']).dt.strftime('%Y-%m')
monthly_sip_inflows.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [121]:
monthly_sip_inflows[monthly_sip_inflows['yoy_growth_pct'].isnull()]
# 2022 year data contains null in yoy_growth_pct because there is no 2021 data to calculate the yoy change

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN
5,2022-06,12276,5.60,7.50,5.18,NaN
6,2022-07,12140,5.65,9.21,5.25,NaN
7,2022-08,12694,5.71,8.90,5.31,NaN
8,2022-09,12976,5.80,9.40,5.41,NaN
9,2022-10,13040,5.93,9.52,5.55,NaN
10,2022-11,13306,6.00,8.80,5.62,NaN
11,2022-12,13573,6.05,7.60,5.70,NaN

In [122]:
monthly_sip_inflows.to_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\monthly_sip_inflows_cleaned.csv",
                         index=False)

##### category_inflows

In [124]:
category_inflows.dtypes

month                   str
category                str
net_inflow_crore    float64
dtype: object

In [126]:
category_inflows.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [128]:
category_inflows.duplicated().sum()

np.int64(0)

In [131]:
category_inflows['category'].unique()

<StringArray>
[        'Large Cap',           'Mid Cap',         'Small Cap',
         'Flexi Cap',   'Large & Mid Cap',              'ELSS',
      'Value/Contra', 'Sectoral/Thematic',            'Liquid',
    'Short Duration',              'Gilt',            'Hybrid']
Length: 12, dtype: str

In [133]:
category_inflows[category_inflows['net_inflow_crore']<0]

Empty DataFrame
Columns: [month, category, net_inflow_crore]
Index: []

In [135]:
category_inflows.to_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\category_inflows_cleaned.csv",
                         index=False)

##### industry_folio_counts

In [138]:
industry_folio_counts.dtypes

month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [140]:
industry_folio_counts.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [142]:
industry_folio_counts.duplicated().sum()

np.int64(0)

In [146]:
# Validating values are greater than 0
industry_folio_counts[industry_folio_counts['total_folios_crore']<0]

Empty DataFrame
Columns: [month, total_folios_crore, equity_folios_crore, debt_folios_crore, hybrid_folios_crore, others_folios_crore]
Index: []

In [148]:
# Validating values are greater than 0
industry_folio_counts[industry_folio_counts['equity_folios_crore']<0]

Empty DataFrame
Columns: [month, total_folios_crore, equity_folios_crore, debt_folios_crore, hybrid_folios_crore, others_folios_crore]
Index: []

In [150]:
# Validating values are greater than 0
industry_folio_counts[industry_folio_counts['debt_folios_crore']<0]

Empty DataFrame
Columns: [month, total_folios_crore, equity_folios_crore, debt_folios_crore, hybrid_folios_crore, others_folios_crore]
Index: []

In [152]:
# Validating values are greater than 0
industry_folio_counts[industry_folio_counts['hybrid_folios_crore']<0]

Empty DataFrame
Columns: [month, total_folios_crore, equity_folios_crore, debt_folios_crore, hybrid_folios_crore, others_folios_crore]
Index: []

In [154]:
# Validating values are greater than 0
industry_folio_counts[industry_folio_counts['others_folios_crore']<0]

Empty DataFrame
Columns: [month, total_folios_crore, equity_folios_crore, debt_folios_crore, hybrid_folios_crore, others_folios_crore]
Index: []

In [156]:
industry_folio_counts.to_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\industry_folio_counts_cleaned.csv",
                         index=False)

##### portfolio_holding

In [158]:
portfolio_holding.dtypes

amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

In [160]:
portfolio_holding.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [164]:
portfolio_holding['portfolio_date']=pd.to_datetime(portfolio_holding['portfolio_date'])
portfolio_holding.dtypes

amfi_code                     int64
stock_symbol                    str
stock_name                      str
sector                          str
weight_pct                  float64
market_value_cr             float64
current_price_inr           float64
portfolio_date       datetime64[us]
dtype: object

In [168]:
portfolio_holding['sector'].unique()

<StringArray>
[     'Utilities',        'Banking',    'Diversified',         'Pharma',
         'Paints',        'Telecom',             'IT',     'Automobile',
           'NBFC',         'Cement',         'Energy', 'Consumer Goods',
           'FMCG', 'Infrastructure']
Length: 14, dtype: str

In [170]:
portfolio_holding[portfolio_holding['market_value_cr']<0]

Empty DataFrame
Columns: [amfi_code, stock_symbol, stock_name, sector, weight_pct, market_value_cr, current_price_inr, portfolio_date]
Index: []

In [173]:
portfolio_holding[portfolio_holding['current_price_inr']<0]

Empty DataFrame
Columns: [amfi_code, stock_symbol, stock_name, sector, weight_pct, market_value_cr, current_price_inr, portfolio_date]
Index: []

In [175]:
portfolio_holding.to_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\portfolio_holding_cleaned.csv",
                         index=False)

##### Benchmak_indices

In [177]:
benchmark_indices.dtypes

date               str
index_name         str
close_value    float64
dtype: object

In [179]:
benchmark_indices.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [182]:
benchmark_indices['date']=pd.to_datetime(benchmark_indices['date'])
benchmark_indices.dtypes

date           datetime64[us]
index_name                str
close_value           float64
dtype: object

In [184]:
benchmark_indices[benchmark_indices['close_value']<0]

Empty DataFrame
Columns: [date, index_name, close_value]
Index: []

In [186]:
benchmark_indices.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [188]:
benchmark_indices.duplicated().sum()

np.int64(0)

In [189]:
benchmark_indices.to_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\processed\benchmark_indices_cleaned.csv",
                         index=False)