#### IMPORTING LIBRARIES

In [1]:
import pandas as pd;

##### IMPORTING DATA

In [2]:
nav_history=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\02_nav_history.csv")
investor_transactions=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\08_investor_transactions.csv")
scheme_performance=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\07_scheme_performance.csv")
fund_master=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\01_fund_master.csv")

###### NAV_HISTORY

In [3]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
# Checking data types
nav_history.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [5]:
# Checking for duplicates
nav_history.duplicated().sum()

np.int64(0)

In [6]:
# checking missing values
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [7]:
# validating nav > 0
nav_history[nav_history['nav']<=0]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [8]:
# changing the STR data type of date into DATE data type
nav_history['date']=pd.to_datetime(
    nav_history['date'])

In [9]:
# Arranging the data in amfi_code and date order
nav_history=nav_history.sort_values(by=['amfi_code','date'],ascending=True)
nav_history

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

##### INVESTOR_TRANSACTIONS

In [10]:
investor_transactions.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [11]:
investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [12]:
# correcting the transaction date column into DATE data type
investor_transactions['transaction_date']=pd.to_datetime(
    investor_transactions['transaction_date'])

In [13]:
# checking any amounts less than zero exists
investor_transactions[investor_transactions['amount_inr']<=0]

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, transaction_type, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status]
Index: []

In [14]:
# checking values in kyc status
investor_transactions['kyc_status'].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

##### SCHEME PERFORMANCE

In [15]:
scheme_performance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [16]:
scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [17]:
# validating expense ratio pct
scheme_performance[scheme_performance['expense_ratio_pct']<=0.1]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [18]:
investor_transactions["transaction_type"] = investor_transactions["transaction_type"].replace("Sip", "SIP")
investor_transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [19]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [20]:
fund_master['launch_date']=pd.to_datetime(fund_master['launch_date'])

In [21]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [22]:
nav_history.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [23]:
investor_transactions.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [24]:
scheme_performance.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [25]:
aum_by_fund_house = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")

In [26]:
aum_by_fund_house['date']=pd.to_datetime(aum_by_fund_house['date'])
aum_by_fund_house.dtypes

date              datetime64[us]
fund_house                   str
aum_lakh_crore           float64
aum_crore                  int64
num_schemes                int64
dtype: object

In [28]:
aum_by_fund_house.columns

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

##### IMPORTING NEW LIBRARY

In [30]:
from sqlalchemy import create_engine

In [32]:
# creating engine
engine = create_engine("sqlite:///../bluestock_mf.db")

In [39]:
# CREATING dim_fund table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE dim_fund(
    amfi_code INTEGER PRIMARY KEY,
    fund_house TEXT,
    scheme_name TEXT,
    category TEXT,
    sub_category TEXT,
    plan TEXT,
    launch_date TEXT,
    benchmark TEXT,
    expense_ratio_pct REAL,
    exit_load_pct REAL,
    min_sip_amount INTEGER,
    min_lumpsum_amount INTEGER,
    fund_manager TEXT,
    risk_category TEXT,
    sebi_category_code TEXT
    )""")
    conn.commit()

OperationalError: (sqlite3.OperationalError) table dim_fund already exists
[SQL:
    CREATE TABLE dim_fund(
    amfi_code INTEGER PRIMARY KEY,
    fund_house TEXT,
    scheme_name TEXT,
    category TEXT,
    sub_category TEXT,
    plan TEXT,
    launch_date TEXT,
    benchmark TEXT,
    expense_ratio_pct REAL,
    exit_load_pct REAL,
    min_sip_amount INTEGER,
    min_lumpsum_amount INTEGER,
    fund_manager TEXT,
    risk_category TEXT,
    sebi_category_code TEXT
    )]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [41]:
# creating dim_table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE dim_date(
     date_id INTEGER PRIMARY KEY,
    full_date TEXT,
    year INTEGER,
    month INTEGER,
    month_name TEXT,
    quarter INTEGER,
    day_of_week TEXT,
    is_weekend INTEGER
    )""")
    conn.commit()

In [42]:
# creating fact_nav
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_nav(
    nav_id INTEGER PRIMARY KEY,
    amfi_code INTEGER,
    date_id INTEGER,
    nav REAL,
    FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code),
    FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
    )""")
    conn.commit()

In [43]:
# creating fact_transactions
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_transactions (
    transaction_id INTEGER PRIMARY KEY,
    investor_id TEXT,
    amfi_code INTEGER,
    date_id INTEGER,
    transaction_type TEXT,
    amount_inr INTEGER,
    state TEXT,
    city TEXT,
    city_tier TEXT,
    age_group TEXT,
    gender TEXT,
    annual_income_lakh REAL,
    payment_mode TEXT,
    kyc_status TEXT,
    FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code),
    FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
    )""")
    conn.commit()

In [44]:
# creating fact_performance table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_performance (
    performance_id INTEGER PRIMARY KEY,
    amfi_code INTEGER,
    return_1yr_pct REAL,
    return_3yr_pct REAL,
    return_5yr_pct REAL,
    benchmark_3yr_pct REAL,
    alpha REAL,
    beta REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    std_dev_ann_pct REAL,
    max_drawdown_pct REAL,
    aum_crore INTEGER,
    expense_ratio_pct REAL,
    morningstar_rating INTEGER,
    risk_grade TEXT,
    FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code)
    )""")
    conn.commit()

In [45]:
# creating fact_aum table
with engine.connect() as conn:
    conn.exec_driver_sql("""
    CREATE TABLE fact_aum (
    aum_id INTEGER PRIMARY KEY,
    date_id INTEGER,
    fund_house TEXT,
    aum_lakh_crore REAL,
    aum_crore INTEGER,
    num_schemes INTEGER,
    FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
    )""")
    conn.commit()

In [46]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", engine)

                name
0           dim_fund
1           dim_date
2           fact_nav
3  fact_transactions
4   fact_performance
5           fact_aum

In [ ]:
# inserting table data into sql database
fund_master.to_sql("dim_fund", engine, if_exists="append", index=False)

In [50]:
nav_history["date"].min(), nav_history["date"].max()

(Timestamp('2022-01-03 00:00:00'), Timestamp('2026-05-29 00:00:00'))

In [51]:
#creating a date range
date_range = pd.date_range(start="2022-01-01", end="2026-12-31", freq="D")
date_range

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25',
               '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=1826, freq='D')

In [52]:
dim_date = pd.DataFrame({
    "full_date": date_range.strftime("%Y-%m-%d"),
    "year": date_range.year,
    "month": date_range.month,
    "month_name": date_range.strftime("%B"),
    "quarter": date_range.quarter,
    "day_of_week": date_range.strftime("%A"),
    "is_weekend": date_range.dayofweek.isin([5, 6]).astype(int)
})

dim_date.head()

    full_date  year  month month_name  quarter day_of_week  is_weekend
0  2022-01-01  2022      1    January        1    Saturday           1
1  2022-01-02  2022      1    January        1      Sunday           1
2  2022-01-03  2022      1    January        1      Monday           0
3  2022-01-04  2022      1    January        1     Tuesday           0
4  2022-01-05  2022      1    January        1   Wednesday           0

In [53]:
dim_date.insert(0, "date_id", range(1, len(dim_date) + 1))
dim_date.head()

,date_id,full_date,year,month,month_name,quarter,day_of_week,is_weekend
0,1,2022-01-01,2022,1,January,1,Saturday,1
1,2,2022-01-02,2022,1,January,1,Sunday,1
2,3,2022-01-03,2022,1,January,1,Monday,0
3,4,2022-01-04,2022,1,January,1,Tuesday,0
4,5,2022-01-05,2022,1,January,1,Wednesday,0

In [54]:
# inseting data into dim_date 
dim_date.to_sql("dim_date", engine, if_exists="append", index=False)

1826

In [55]:
pd.read_sql("SELECT * FROM dim_date LIMIT 5;", engine)

,date_id,full_date,year,month,month_name,quarter,day_of_week,is_weekend
0,1,2022-01-01,2022,1,January,1,Saturday,1
1,2,2022-01-02,2022,1,January,1,Sunday,1
2,3,2022-01-03,2022,1,January,1,Monday,0
3,4,2022-01-04,2022,1,January,1,Tuesday,0
4,5,2022-01-05,2022,1,January,1,Wednesday,0

In [56]:
dim_date_lookup = pd.read_sql("SELECT date_id, full_date FROM dim_date;", engine)
dim_date_lookup["full_date"] = pd.to_datetime(dim_date_lookup["full_date"])
dim_date_lookup.head()

   date_id  full_date
0        1 2022-01-01
1        2 2022-01-02
2        3 2022-01-03
3        4 2022-01-04
4        5 2022-01-05

In [57]:
# inserting data inside fact_nav
fact_nav = nav_history.merge(dim_date_lookup, left_on="date", right_on="full_date", how="left")
fact_nav.head()

   amfi_code       date       nav  date_id  full_date
0     100016 2022-01-03  520.4608        3 2022-01-03
1     100016 2022-01-04  515.0971        4 2022-01-04
2     100016 2022-01-05  521.7239        5 2022-01-05
3     100016 2022-01-06  515.7880        6 2022-01-06
4     100016 2022-01-07  515.1639        7 2022-01-07

In [58]:
fact_nav = fact_nav[["amfi_code", "date_id", "nav"]]
fact_nav.head()

   amfi_code  date_id       nav
0     100016        3  520.4608
1     100016        4  515.0971
2     100016        5  521.7239
3     100016        6  515.7880
4     100016        7  515.1639

In [59]:
fact_nav.to_sql("fact_nav",engine, if_exists='append',index=False)
pd.read_sql("SELECT * FROM fact_nav LIMIT 5;", engine)

   nav_id  amfi_code  date_id       nav
0       1     100016        3  520.4608
1       2     100016        4  515.0971
2       3     100016        5  521.7239
3       4     100016        6  515.7880
4       5     100016        7  515.1639

In [64]:
investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [65]:
dim_date_lookup.head()

   date_id  full_date
0        1 2022-01-01
1        2 2022-01-02
2        3 2022-01-03
3        4 2022-01-04
4        5 2022-01-05

In [66]:
# merging the tables
fact_transactions=investor_transactions.merge(dim_date_lookup,left_on ='transaction_date',right_on='full_date',how='left')
fact_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status,date_id,full_date
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified,731,2024-01-01
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified,731,2024-01-01
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified,731,2024-01-01
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending,731,2024-01-01
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending,731,2024-01-01

In [68]:
# removing unwanted columns (transaction_date,full_dates)
fact_transactions=fact_transactions[['investor_id','amfi_code','date_id','transaction_type','amount_inr','state','city','city_tier',
                                     'age_group','gender','annual_income_lakh','payment_mode','kyc_status']]
fact_transactions.head()

,investor_id,amfi_code,date_id,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,119092,731,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,148567,731,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,118636,731,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,118634,731,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,119094,731,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [69]:
# loading data into sql fact_transaction
fact_transactions.to_sql("fact_transactions", engine, if_exists="append", index=False)
pd.read_sql("SELECT * FROM fact_transactions LIMIT 5;", engine)

,transaction_id,investor_id,amfi_code,date_id,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,1,INV003054,119092,731,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,2,INV002952,148567,731,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,3,INV003420,118636,731,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,4,INV003436,118634,731,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,5,INV004691,119094,731,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [70]:
scheme_performance.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [72]:
# Drop duplicate columns (columns already in dim_fund)
fact_performance = scheme_performance.drop(columns=["scheme_name", "fund_house", "category", "plan"])
fact_performance.head()

,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [74]:
# loading data 
fact_performance.to_sql("fact_performance", engine, if_exists="append", index=False)
pd.read_sql("SELECT * FROM fact_performance LIMIT 5;",engine)

,performance_id,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,1,119551,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,2,119552,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,3,119598,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,4,119599,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,5,119120,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [76]:
# importing aum_by_fund_house data
aum_by_fund_house=pd.read_csv(r"C:\Users\aksha\OneDrive\Desktop\BLUE STOCK INTERNSHIP\Mutual-Fund-Analysis\data\raw\03_aum_by_fund_house.csv")
aum_by_fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [77]:
aum_by_fund_house.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [78]:
# changing date into Date data ype
aum_by_fund_house['date']=pd.to_datetime(aum_by_fund_house['date'])

In [80]:
dim_date_lookup.head()

   date_id  full_date
0        1 2022-01-01
1        2 2022-01-02
2        3 2022-01-03
3        4 2022-01-04
4        5 2022-01-05

In [82]:
# merging for including date_id column in aum
fact_aum=aum_by_fund_house.merge(dim_date_lookup,left_on='date',right_on='full_date',how='left')
fact_aum.head()

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes,date_id,full_date
0,2022-03-31,SBI Mutual Fund,6.05,605000,186,90,2022-03-31
1,2022-03-31,ICICI Prudential MF,4.65,465000,216,90,2022-03-31
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195,90,2022-03-31
3,2022-03-31,Nippon India MF,2.70,270000,177,90,2022-03-31
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168,90,2022-03-31

In [83]:
fact_aum = fact_aum[["date_id", "fund_house", "aum_lakh_crore", "aum_crore", "num_schemes"]]
fact_aum.head()

   date_id           fund_house  aum_lakh_crore  aum_crore  num_schemes
0       90      SBI Mutual Fund            6.05     605000          186
1       90  ICICI Prudential MF            4.65     465000          216
2       90     HDFC Mutual Fund            4.35     435000          195
3       90      Nippon India MF            2.70     270000          177
4       90    Kotak Mahindra MF            2.70     270000          168

In [85]:
fact_aum.to_sql("fact_aum", engine, if_exists="append", index=False)
pd.read_sql('SELECT * FROM fact_aum LIMIT 5;',engine)

,aum_id,date_id,fund_house,aum_lakh_crore,aum_crore,num_schemes
0,1,90,SBI Mutual Fund,6.05,605000,186
1,2,90,ICICI Prudential MF,4.65,465000,216
2,3,90,HDFC Mutual Fund,4.35,435000,195
3,4,90,Nippon India MF,2.70,270000,177
4,5,90,Kotak Mahindra MF,2.70,270000,168

In [90]:
print("dim_fund:", pd.read_sql("SELECT COUNT(*) FROM dim_fund;", engine).iloc[0,0], "vs fund_master:", fund_master.shape[0])
print("fact_nav:", pd.read_sql("SELECT COUNT(*) FROM fact_nav;", engine).iloc[0,0], "vs nav_history:", nav_history.shape[0])
print("fact_transactions:", pd.read_sql("SELECT COUNT(*) FROM fact_transactions;", engine).iloc[0,0], "vs investor_transactions:", investor_transactions.shape[0])
print("fact_performance:", pd.read_sql("SELECT COUNT(*) FROM fact_performance;", engine).iloc[0,0], "vs scheme_performance:", scheme_performance.shape[0])
print("fact_aum:", pd.read_sql("SELECT COUNT(*) FROM fact_aum;", engine).iloc[0,0], "vs aum_by_fund_house:", aum_by_fund_house.shape[0])

dim_fund: 40 vs fund_master: 40
fact_nav: 46000 vs nav_history: 46000
fact_transactions: 32778 vs investor_transactions: 32778
fact_performance: 40 vs scheme_performance: 40
fact_aum: 90 vs aum_by_fund_house: 90

In [87]:
with engine.connect() as conn:
    conn.exec_driver_sql("DELETE FROM fact_performance;")
    conn.exec_driver_sql("DELETE FROM fact_aum;")
    conn.commit()

In [88]:
fact_performance.to_sql("fact_performance", engine, if_exists="append", index=False)
fact_aum.to_sql("fact_aum", engine, if_exists="append", index=False)

90

In [89]:
print("fact_performance:", pd.read_sql("SELECT COUNT(*) FROM fact_performance;", engine).iloc[0,0], "vs scheme_performance:", scheme_performance.shape[0])
print("fact_aum:", pd.read_sql("SELECT COUNT(*) FROM fact_aum;", engine).iloc[0,0], "vs aum_by_fund_house:", aum_by_fund_house.shape[0])

fact_performance: 40 vs scheme_performance: 40
fact_aum: 90 vs aum_by_fund_house: 90